### ISSUE TITLE
requests-oauthlib needs to be reinstalled in edxapp venv

### ISSUE THREAD

**Issue by tusbar** [IONISx/edx-configuration#1]
```
2014-06-12 21:54:23,434 ERROR 31065 [gunicorn.error] glogging.py:219 - Error handling request
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
    response = self.get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 179, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 227, in handle_uncaught_exception
    callback, param_dict = resolver.resolve500()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 370, in resolve500
    return self._resolve_special('500')
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 361, in _resolve_special
    return get_callable(callback), {}
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/functional.py", line 27, in wrapper
    result = func(*args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 93, in get_callable
    lookup_view = getattr(import_module(mod_name), func_name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/__init__.py", line 16, in <module>
    from .public import *
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/public.py", line 12, in <module>
    from external_auth.views import (ssl_login_shortcut, ssl_get_cert_from_request,
  File "/edx/app/edxapp/edx-platform/common/djangoapps/external_auth/views.py", line 47, in <module>
    import student.views
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 86, in <module>
    from third_party_auth import pipeline, provider
  File "/edx/app/edxapp/edx-platform/common/djangoapps/third_party_auth/pipeline.py", line 70, in <module>
    from . import provider
  File "/edx/app/edxapp/edx-platform/common/djangoapps/third_party_auth/provider.py", line 7, in <module>
    from social.backends import google, linkedin
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social/backends/google.py", line 8, in <module>
    from social.backends.oauth import BaseOAuth2, BaseOAuth1
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social/backends/oauth.py", line 4, in <module>
    from requests_oauthlib import OAuth1
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests_oauthlib/__init__.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests_oauthlib/oauth1_auth.py", line 10, in <module>
    from requests.utils import to_native_string
ImportError: cannot import name to_native_string
```

To fix (in `edxapp` venv):

```
pip install requests-oauthlib --upgrade --force
```

**Comment by ilashari** [comment]
Thanx

**Comment by uayyappa** [comment]
Thank you very much

**Comment by pzrq** [comment]
Thanks.

This came up with python-social-auth under OSX 10.10 Yosemite, Python 2.7.6 and the fix tusbar mentioned above works:

```
pip install requests-oauthlib --upgrade --force
```

**Comment by tusbar** [comment]
Keep in mind that this fix worked as of June 12th as the latest version of `requests-oauthlib` was required. :)
But you should always install the version specified in [Open edX’s requirements](https://github.com/edx/edx-platform/blob/master/requirements/edx/base.txt#L74) that’s matching your version of the platform, of course.

**Comment by sibtey** [comment]
Thanks a lot
